#自定义微服务名称
spring:
  application:
    name: eureka-server
  cloud:
    inetutils:
      ignored-interfaces:
        - VMware.*  # 忽略虚拟机网卡
      use-only-site-local-interfaces: true
      preferred-networks: 192.168.0.* # 优先使用 192.168.0.*


server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点

eureka:
  hostname: localhost
  #暴露eureka服务的地址
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:${server.port}/eureka/
    #是否注册到eureka
    registerWithEureka: false
    #是否从eureka中拉取注册信息
    fetchRegistry: false
    # 关闭自我保护
  server:
    enable-self-preservation: true
    #清除无效节点，时间间隔为10秒
    eviction-interval-timer-in-ms: 1000